builds:
  - binary: mirrorful-cli
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: mirrorful
    homepage: "https://github.com/Mirrorful/mirrorful"
    tap:
      owner: Mirrorful
      name: homebrew-mirrorful
    commit_author:
      name: alexdanilowicz
      email: alex.danilowicz@gmail.com

checksum:
  name_template: "checksums.txt"
