# .goreleaser.yml

project_name: cli

builds:
  - binary: cli
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    id: "cli"
    dir: .
    main: ./cli/cmd
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: cli
    homepage: "https://github.com/Mirrorful/mirrorful"
    tap:
      owner: Mirrorful
      name: homebrew-mirrorful
    commit_author:
      name: alexdanilowicz
      email: alex@mirrorful.io

checksum:
  name_template: "checksums.txt"
